ACCOUNT_CREATED = "ACCOUNT_CREATED"

USERNAME_ALREADY_EXISTS = "USERNAME_ALREADY_EXISTS"

USERNAME_INVALID = "USERNAME_INVALID"

PASSWORD_INVALID = "PASSWORD_INVALID"

ACCOUNT_LIMIT_REACHED = "ACCOUNT_LIMIT_REACHED"

MISSING_VERIFIED_ROLE = "MISSING_VERIFIED_ROLE"

COOLDOWN_ACTIVE = "COOLDOWN_ACTIVE"

DISCORD_ACCOUNT_TOO_NEW = "DISCORD_ACCOUNT_TOO_NEW"

UNKNOWN_ERROR = "UNKNOWN_ERROR"
